name: com.example.flutter_cubit_example
description: A simple Flutter application demonstrating Cubit pattern for state management with a login screen and a home screen.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.1.0

flutter:
  uses-material-design: true